export const courseData = {
  "opsc-oas": {
    "physics-wallah": {
      name: "Sarv Saksham OPSC OAS Foundation Batch 2024-26",
      platform: "Physics Wallah",
      logo: "🎯",
      price: "₹7,999",
      offer: "₹1,999",
      rating: 4.0,
      link: "https://www.pw.live/state-psc/opsc/batches",
    },
    adda247: {
      name: "OPSC OCS (Pre + Mains + Interview) Foundation",
      platform: "Adda247",
      logo: "📚",
      price: "₹15,624",
      offer: "₹10,936",
      rating: 3.8,
      link: "https://www.adda247.com/odisha-state-exams-study-materials",
    },
    studyiq: {
      name: "Paripurna OPSC OCS (Pre + Mains) Foundation Batch",
      platform: "StudyIQ",
      logo: "🎓",
      price: "₹8,000",
      offer: null,
      rating: 3.5,
      link: "https://www.studyiq.com/course-detail/paripurna-opsc-ocs-pre-mains-foundation-2025-26-batch",
    },
    "vanik-institute": {
      name: "GS Foundation (Offline: 12 Months)",
      platform: "Vanik Institute",
      logo: "🏛️",
      price: "Approx. ₹1,05,000",
      offer: null,
      rating: 4.2,
      link: "https://www.vanik.org",
    },
  },
  "opsc-aso": {
    "physics-wallah": {
      name: "OPSC ASO Foundation Batch 2024-26",
      platform: "Physics Wallah",
      logo: "🎯",
      price: "₹6,999",
      offer: "₹1,799",
      rating: 4.1,
      link: "https://www.pw.live/state-psc/opsc/batches",
    },
    adda247: {
      name: "OPSC ASO (Pre + Mains) Complete Course",
      platform: "Adda247",
      logo: "📚",
      price: "₹12,999",
      offer: "₹8,999",
      rating: 3.9,
      link: "https://www.adda247.com/odisha-state-exams-study-materials",
    },
    studyiq: {
      name: "OPSC ASO Complete Foundation Course",
      platform: "StudyIQ",
      logo: "🎓",
      price: "₹7,500",
      offer: null,
      rating: 3.6,
      link: "https://www.studyiq.com",
    },
    "vanik-institute": {
      name: "ASO Foundation Course (Offline)",
      platform: "Vanik Institute",
      logo: "🏛️",
      price: "Approx. ₹85,000",
      offer: null,
      rating: 4.0,
      link: "https://www.vanik.org",
    },
  },
  "ossc-cgl": {
    "physics-wallah": {
      name: "OSSC CGL Foundation Batch 2024-26",
      platform: "Physics Wallah",
      logo: "🎯",
      price: "₹5,999",
      offer: "₹1,599",
      rating: 4.2,
      link: "https://www.pw.live/state-psc/ossc/batches",
    },
    adda247: {
      name: "OSSC CGL Complete Course",
      platform: "Adda247",
      logo: "📚",
      price: "₹10,999",
      offer: "₹7,999",
      rating: 3.7,
      link: "https://www.adda247.com/odisha-state-exams-study-materials",
    },
    studyiq: {
      name: "OSSC CGL Foundation Course",
      platform: "StudyIQ",
      logo: "🎓",
      price: "₹6,500",
      offer: null,
      rating: 3.4,
      link: "https://www.studyiq.com",
    },
    "vanik-institute": {
      name: "CGL Foundation (Offline)",
      platform: "Vanik Institute",
      logo: "🏛️",
      price: "Approx. ₹75,000",
      offer: null,
      rating: 4.1,
      link: "https://www.vanik.org",
    },
  },
  "ossc-chsl": {
    "physics-wallah": {
      name: "OSSC CHSL Foundation Batch 2024-26",
      platform: "Physics Wallah",
      logo: "🎯",
      price: "₹4,999",
      offer: "₹1,299",
      rating: 4.0,
      link: "https://www.pw.live/state-psc/ossc/batches",
    },
    adda247: {
      name: "OSSC CHSL Complete Course",
      platform: "Adda247",
      logo: "📚",
      price: "₹8,999",
      offer: "₹6,499",
      rating: 3.8,
      link: "https://www.adda247.com/odisha-state-exams-study-materials",
    },
    studyiq: {
      name: "OSSC CHSL Foundation Course",
      platform: "StudyIQ",
      logo: "🎓",
      price: "₹5,500",
      offer: null,
      rating: 3.5,
      link: "https://www.studyiq.com",
    },
    "vanik-institute": {
      name: "CHSL Foundation (Offline)",
      platform: "Vanik Institute",
      logo: "🏛️",
      price: "Approx. ₹65,000",
      offer: null,
      rating: 3.9,
      link: "https://www.vanik.org",
    },
  },
  "osssc-ri": {
    "physics-wallah": {
      name: "OSSSC RI Foundation Batch 2024-26",
      platform: "Physics Wallah",
      logo: "🎯",
      price: "₹4,499",
      offer: "₹1,199",
      rating: 3.9,
      link: "https://www.pw.live/state-psc/osssc/batches",
    },
    adda247: {
      name: "OSSSC RI Complete Course",
      platform: "Adda247",
      logo: "📚",
      price: "₹7,999",
      offer: "₹5,999",
      rating: 3.6,
      link: "https://www.adda247.com/odisha-state-exams-study-materials",
    },
    studyiq: {
      name: "OSSSC RI Foundation Course",
      platform: "StudyIQ",
      logo: "🎓",
      price: "₹5,000",
      offer: null,
      rating: 3.3,
      link: "https://www.studyiq.com",
    },
    "vanik-institute": {
      name: "RI Foundation (Offline)",
      platform: "Vanik Institute",
      logo: "🏛️",
      price: "Approx. ₹55,000",
      offer: null,
      rating: 3.8,
      link: "https://www.vanik.org",
    },
  },
  "odisha-aao": {
    "physics-wallah": {
      name: "Odisha AAO Foundation Batch 2024-26",
      platform: "Physics Wallah",
      logo: "🎯",
      price: "₹6,499",
      offer: "₹1,699",
      rating: 4.1,
      link: "https://www.pw.live/state-psc/aao/batches",
    },
    adda247: {
      name: "Odisha AAO Complete Course",
      platform: "Adda247",
      logo: "📚",
      price: "₹11,999",
      offer: "₹8,499",
      rating: 3.8,
      link: "https://www.adda247.com/odisha-state-exams-study-materials",
    },
    studyiq: {
      name: "Odisha AAO Foundation Course",
      platform: "StudyIQ",
      logo: "🎓",
      price: "₹7,000",
      offer: null,
      rating: 3.5,
      link: "https://www.studyiq.com",
    },
    "vanik-institute": {
      name: "AAO Foundation (Offline)",
      platform: "Vanik Institute",
      logo: "🏛️",
      price: "Approx. ₹95,000",
      offer: null,
      rating: 4.0,
      link: "https://www.vanik.org",
    },
  },
}

export const examCategories = [
  { id: "opsc-oas", name: "OPSC OAS", icon: "BookOpen" },
  { id: "opsc-aso", name: "OPSC ASO", icon: "Users" },
  { id: "ossc-cgl", name: "OSSC CGL", icon: "Award" },
  { id: "ossc-chsl", name: "OSSC CHSL", icon: "TrendingUp" },
  { id: "osssc-ri", name: "OSSSC RI", icon: "Clock" },
  { id: "odisha-aao", name: "Odisha AAO", icon: "Star" },
]

export const topPlatforms = [
  { id: "physics-wallah", name: "Physics Wallah", logo: "🎯" },
  { id: "adda247", name: "Adda247", logo: "📚" },
  { id: "studyiq", name: "StudyIQ", logo: "🎓" },
  { id: "vanik-institute", name: "Vanik Institute", logo: "🏛️" },
]
